# Generated by Django 4.2.5 on 2023-09-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
