# Generated by Django 4.2.5 on 2023-09-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_taskmanager_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='task_date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='task_time',
            field=models.TimeField(auto_now=True, verbose_name='время публикации'),
        ),
    ]
