# Generated by Django 4.2.5 on 2023-09-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_taskmanager_task_date_alter_taskmanager_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='task_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='task_time',
            field=models.TimeField(verbose_name='время публикации'),
        ),
    ]
